name: Check build
on:
  push:
    branches:
      - mmiyoo/joystick
  merge_group:
  pull_request:

jobs:
  build:
    name: Check build
    runs-on: ubuntu-latest
    container:
      image: aemiii91/miyoomini-toolchain:latest
      options: --user root
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      shell: bash
      run: |
        source /root/.bashrc
        ./ci/build.sh
    - name: Store build output as artifact
      uses: actions/upload-artifact@v3
      with:
        name: libSDL2-miyoo-mini-plus
        path: install/